# Generated by Django 5.0.2 on 2024-08-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('VIP1', 'VIP1'), ('VIP2', 'VIP2'), ('VIP3', 'VIP3')], max_length=5),
        ),
    ]
