# Generated by Django 5.0.2 on 2024-07-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('superAdmin', 'SuperAdmin'), ('client', 'Client')], max_length=10),
        ),
    ]
